//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registration_Tren
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        public int IdGame { get; set; }
        public string NameGame { get; set; }
        public byte[] FotoGame { get; set; }
    }
}
